Getting the Crane Runner project started
konveyor/crane-runner pull request #1
Opened 2021-12-02 15:47 UTC by djzager

This PR includes a few things:

* The Dockerfile for creating the `crane-runner` image.
* ClusterTask manifests that make use of the `crane-runner` image + kustomize overlays to make them easy to install.
* A `hack` directory for scripts to startup/shutdown kind or minikube clusters as well as handle installing Tekton and whatever else we may want to do.
* An examples directory.

2021-12-03 12:10 UTC, JaydipGabani commented on examples/001_stateless-app-mirror/README.md
> +* Create [Tekton PipelineRun](https://kubernetes.io/docs/tutorials/stateless-application/guestbook/)
@djzager may be the link for creating tekton pipeline is needed here instead of creating a stateless application.

2021-12-08 04:26 UTC, eriknelson requested changes
I was able to run through the first example using the small adjustments David
specified in [slack](https://coreos.slack.com/archives/C02ELCA262K/p1638914261267800?thread_ts=1638908862.264300&cid=C02ELCA262K).

I started with a fresh install of Fedora 35 Server on a bare metal machine I had
lying around. Installed podman and minikube, and finished the exercise in about
90 minutes. This is really cool stuff.

Some general thoughts as I try to distill the notes I took running it:

* We should probably not block this PR from merging on completion of the other
examples so that we can get stuff merged and not have to use custom paths for
the kustomize commands and work to merge Alay's PR.

* I stopped firewalld, is that actually required so the networking between
the minikube clusters can be functional?
* I had some issues with the minikube script initially:

```
# ./minikube-clusters-start.sh
🤷  Profile "src" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start -p src"
```

Had to comment out these lines from the minikube script:

```
  8 minikube status -p ${SRC_CLUSTER_NAME} && echo "run hack/minikube-delete-clusters.sh before running this script"; exit 1¬
  9 minikube status -p ${DEST_CLUSTER_NAME} && echo "run hack/minikube-delete-clusters.sh before running this script"; exit 1¬
```

minikube info:

```
# mk version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b
```

Once I removed these lines it ran flawlessly to completion.

* I started at the top level example readme and ran through the installation
of tekton and our cluster tasks in my default `minikube start` cluster, then
realized I actually needed to run Alay's script to get my src and dest clusters
with the contexts setup, so I backpedaled and deleted the deafult cluster. I'm
not sure there's anything we should do here other than to link to the examples/README.md
file and maybe metion there that all the examples will use the environment that
we setup with the minikube script, and give some explanation as to what that
looks like.

* I don't think this will be necessary for the demo but might want to call out
that if the user is using podman they'll need to use RUNTIME for their make
commands.

* I had to wrap the kustomize build command in some cases with single quotes
in my weird zsh setup. The command in the top level readme needed it, but elsewhere
David escaped the ?, so it worked fine without it there. Let's just escape it
on the top level one so they're all consistent.

* The actual TaskRun steps in the first tutorial don't have any explanation about
what they're doing, do we want to add a link to the upstream crane cli docs
so the tutorial follower can read about what the commands do and why?

Honestly I think that's all I've got for a first pass, this is awesome and
is really cool to see even the first demo prove a lot of the MTX architecture.
Again I'd advocate let's get this merged with the rest of the examples stubbed
and fill in each with follow on PRs.

2021-12-08 04:26 UTC, eriknelson commented on README.md
> +kustomize build github.com/konveyor/crane-runner/manifests?ref=master | kubectl apply -f -
This was the command that needed the ? escaped.

2021-12-09 13:08 UTC, eriknelson approved these changes

2021-12-09 13:08 UTC, merged