fixups: correct the branch names in doc and flags in transform cmd
konveyor/crane-runner pull request #3
Opened 2021-12-09 16:17 UTC by alaypatel07

2021-12-09 19:07 UTC, djzager requested changes
Drop the ref on the `kustomize build`s and don't forget the README.md at project root

2021-12-09 19:07 UTC, djzager commented on examples/001_stateless-app-mirror/README.md
> +kustomize build github.com/konveyor/crane-runner/manifests\?ref=main | kubectl --context dest apply -f -
```suggestion
kustomize build github.com/konveyor/crane-runner/manifests | kubectl --context dest apply -f -
```
Turns out we can just drop the ref.

2021-12-10 14:32 UTC, alaypatel07 commented on examples/001_stateless-app-mirror/README.md
> +kustomize build github.com/konveyor/crane-runner/manifests\?ref=main | kubectl --context dest apply -f -
Updated PTAL

2021-12-10 15:48 UTC, djzager approved these changes

2021-12-10 16:50 UTC, merged